### PR TITLE
Upgrade aiokafka version to 0.6.0

### PR DESCRIPTION
**Pull request by kgaikwad**
There are couple of `pyup-scheduled-update-*` branches which suggest to upgrade aiokafka version.
While working on different ticket added few changes around this change so thought to open a pull-request.

+adding @beav into the loop.

### CODE REVIEW

**Comment by kgaikwad** [comment]
@abaiken , @kholdaway,
Hello, I added you as reviewer for these changes. As per me, I covered changes in all configuration files that are required when there is any version change for dependencies.
If I am missing anything could you please guide me on this.

**Comment by kholdaway** [comment]
If you didn't discover any issues while testing, these changes look fine to me.  I will let one of your team members click the official approve button.

**Review by beav — APPROVED** [review]

**Review by patilsuraj767 — APPROVED** [review]
Tested the PR on local dev setup. The test was successful, did not saw any error logs in Yupana and Kafka. Report_consumer was able to consume from qpc topic and Report_slice_processor was able to push the host to host-ingress kafka topic. Green signal for aiokafka-0.6.0 :tada:

LGTM :+1:

**Comment by patilsuraj767** [comment]
Thanks @kgaikwad

**Pull request merged**
