### PR TITLE
[YUPANA-110] ESB to org_id level 3 changes

### PR DESCRIPTION
**Pull request by patilsuraj767**

### CODE REVIEW

**Review by kgaikwad — APPROVED** [review]
@patilsuraj767 - looks good to me.
Note that as these changes mainly altered the prometheus metrics, once it is in stage one needs to confirm Grafana dashboard for Subscriptions (Yupana).

**Comment by kgaikwad** [comment]
@patilsuraj767 - as part of level 3, I think you will also need to set `allow_null=True` for `account` and not nullable for `org_id`, correct?

**Comment by patilsuraj767** [comment]
@kgaikwad account was already set to `null=True` [here](https://github.com/quipucords/yupana/blob/1009f48c723f48fa3d0d0765d1da170f3eb74a7f/yupana/api/report/model.py#L24) and regarding org_id, it is also set to null=True because we neither use account or org_id for querying database. But we are checking that incoming report/message has the `org_id` [here](https://github.com/quipucords/yupana/blob/1009f48c723f48fa3d0d0765d1da170f3eb74a7f/yupana/processor/report_consumer.py#L137) if not then Exception is raised.

**Comment by kgaikwad** [comment]
> @kgaikwad account was already set to `null=True` [here](https://github.com/quipucords/yupana/blob/1009f48c723f48fa3d0d0765d1da170f3eb74a7f/yupana/api/report/model.py#L24) and regarding org_id, it is also set to null=True because we neither use account or org_id for querying database. But we are checking that incoming report/message has the `org_id` [here](https://github.com/quipucords/yupana/blob/1009f48c723f48fa3d0d0765d1da170f3eb74a7f/yupana/processor/report_consumer.py#L137) if not then Exception is raised.

Got it! Then it won't require additional work as part of level 3

**Pull request merged**
