### PR TITLE
YUPANA #60 Set configs for CLOWDER_ENABLED

### PR DESCRIPTION
**Pull request by apuntamb**

### CODE REVIEW

**Comment by apuntamb** [comment]
@kgaikwad Can you take a look once to verify if something else you feel should be made specific to Clowder and Non-Clowder?
For reference -> https://github.com/RedHatInsights/vulnerability-engine/blob/master/common/config.py

**Review by kgaikwad — CHANGES_REQUESTED** [review]
Thanks @apuntamb,
Added one inline comment.
Secondly, any specific reason you haven't initialized kafka topics using `KafkaTopics` from app_common_python?

**Review by kgaikwad — APPROVED** [review]
I haven't tested it but looks good codewise.

**Comment by r14chandra** [comment]
@apuntamb I tested it locally (with an archive upload). Not getting any errors on  processors logs.

**Comment by apuntamb** [comment]
Thanks @kgaikwad and @r14chandra for the review. Merging this.

**Pull request merged**
