### PR TITLE
Release of Yupana 0.2.13

### PR DESCRIPTION
**Pull request by kgaikwad**
### Commit

`5af42cf213e733a361d9fbe5441a6dc77552596e`

### Features

- [PR 363](https://github.com/quipucords/yupana/pull/363) - Update rbac to service set in Jenkinsfile-smoke.groovy
- [PR 361](https://github.com/quipucords/yupana/pull/361) - Update Jenkinsfile-smoke.groovy
- [PR 358](https://github.com/quipucords/yupana/pull/358) - Update stale_timestamp to same as insights-client
- [PR 356](https://github.com/quipucords/yupana/pull/356) - Transform tag's value to string
- [PR 350](https://github.com/quipucords/yupana/pull/350) - Transform bios UUID field to omit invalid value
- [PR 354](https://github.com/quipucords/yupana/pull/354) - Migrate from Travis to GitHub actions
- [PR 352](https://github.com/quipucords/yupana/pull/352) - Update smoke job to use the foreman IQE plugin

### Bugs
- [PR 362](https://github.com/quipucords/yupana/pull/362) - print log only when tags are transformed by yupana
- [PR 359](https://github.com/quipucords/yupana/pull/359) - Refs YUPANA-42 omit bios_uuid of type boolean & number
- [PR 355](https://github.com/quipucords/yupana/pull/355) - remove slack notification step

### CODE REVIEW

**Comment by kgaikwad** [comment]
@apuntamb - please request to review release changes.

**Comment by apuntamb** [comment]
@kgaikwad LGTM! I see one of the checks still running. Once that's done, we can merge the PR.

**Comment by kgaikwad** [comment]
> @kgaikwad LGTM! I see one of the checks still running. Once that's done, we can merge the PR.

As we are using github actions instead of travis, removed `continuous-integration/travis-ci` from list under `Require status checks to pass before merging` for status branch.

**Comment by kgaikwad** [comment]
Thank you @apuntamb for review!

**Pull request merged**
