### PR TITLE
Adds PR check capabilty to yupana repo

### PR DESCRIPTION
**Pull request by san7ket**

### CODE REVIEW

**Comment by san7ket** [comment]
Is the job error related ? 

please advise on how to fix the build errors.

**Comment by apuntamb** [comment]
@san7ket can you push any change on top of this commit?

**Comment by san7ket** [comment]
bump

**Comment by patilsuraj767** [comment]
@san7ket rebase the PR after this - https://github.com/quipucords/yupana/pull/395 is merged and then retest.

**Comment by apuntamb** [comment]
@san7ket Hello! The related PR #395 is now merged. Could you rebase and push the commit to this PR now, let's see if that triggers the job to the ci.ext jenkins.

**Review by kgaikwad — APPROVED** [review]

**Comment by kgaikwad** [comment]
@san7ket - Job is not yet triggered.

**Pull request merged**
